name: Contidions Demp

on:
  workflow_dispatch:

jobs:
  conditional-job:
    runs-on: ubuntu-latest
    steps:
      - name: Always runs
        run: echo "This always is runs"

      - name: Runs only if prev step succeeded
        if: success()
        run: echo "Previous step succeeded"

      - name: Simulating a failing step
        run: | 
          echo "Step fails Internationally"
          exit 1

      - name: Runs only id the previous step failes
        if: dailure()
        run: echo "Previous step fails, therefore I run"
