name: Matrix Demo

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [9.0, 8.0]

    steps:
      - name: setup .Net
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: ${{ matrix.version }}

      - name: build solution
        run: dotnet build

      - name: Print matrix values
        run: |
          echo "Running on OS: ${{ matrix.os }}"
          echo "Using .Net version: ${{matrix.version}}
